---
title: "DAL Assignment 2"
author: "Heber Ng"
date: "2018年10月16日"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Analyics Lab Assignment 2

# Line of Analysis (Remove)

1) Segregate the projects based on similar features
2) Segregate the donors
3) Check the donor's donation distribution to each cluster of project for each cluster of doners

## Objective

The objective of the analysis is to find if there are different clusters of donors in the dataset and the kind of projects that will appeal to them. The analysis will also examine if the presentation of the projects matters to different kind of donors.

To achieve the analysis, both the donors and projects are subjected to clustering analysis to group both sides according to common features. The list of features are curated based on the website interface on [DonorsChoose's](https://www.donorschoose.org/donors/search.html) project search page These features differs between the 2 and are listed below:

Projects Features:
- Location of the School
- Is the school a rural school? (School Metro Type == rural)
- Does more than half of the students of the school comes from low income families (School Percentage Free Lunch > 50)
- Has the school successfully funded a project before
- Gender of the Teacher proposing the project (May not be feasible based on Teacher Prefix alone as the teacher's profile picture, or the lack of, is shown on the page itself)
- Number of years in experience of the Teacher in initiating projects
- Has the teacher successfully funded a project before
- Project Theme (Sentiment/Text analysis)
- Project Type (Teacher/Student Led, Professional Development)
- Project Grade Level Category
- Project Subject Category Tree (bitflag according to "Applied Learning", "Health & Sports", "History & Civics", "Literacy & Language", "Math & Science", "Music & The Arts", "Special Needs", "Warmth, Care & Hunger")
- Project Subject Subcategory Tree (May not be used as the subcategory is now shown on the inteface)
- Project Resource Category (a.k.a. what was requested)
- Project Cost (Classified according to the )

Projects clustering involves identifying similar projects based on location, school type, project proposal, project type, resource required and cost. Each project are assigned a group value to be used in Donor analysis.

Donors Features:
- The group value of the project that the donor donates to
- Donor's Loacation
- Donor's proximity to the School (Same State/Different State or more?)
- Is Donor a teacher?
- Does Donor include optional donation (15% to organization)
- Amount donated on each donation
- Sense of urgency (How close is the donation date to the expiry date of the project?)
- Does the project have pre-existing donations at the point when the donor donated? 

## Data Cleaning

### Donor

- Perfomed missing data pattern on the table. Found 1909543 complete observations, 33037 observations with missing Donor City values and 180060 observations with missing Donor City and Donor Zip values.

- Observations with missing Donor City are not really much of a concern as the first 3 numbers of the zip code will suffice in identify the proximity of the donor to the proximity of the school. Distribution analysis performed on the Donor State and Donor Is Teacher varialbe shows that these observations are spreaded across different states and teacher status, indicating that the missing value may not be caused by data malfunctions. Therefore those observations are included in the clean dataset

- Observations with both missing Donor City and Donor Zip are likewise subjected to further distribution analysis: the result reveals that roughly half of these observations have a Donor State value of "other", implying that these donors originated from out of United States. Such observations should be considered valid as these donors will not have a valid zip code. Observations with a non "other" Donor State value but with missing Donor Zip values are flagged out using a formula column Incomplete Location Info.

- Flagging out the observations with incomplete location info is chosen over hiding and exluding action because the data given exists in a relational database form. Future exploratory analysis may require joining of the Donors table with other tables, in which the hidden and excluded rows may cause instances of missing data in the joined table

- Summary statistics and distribtuion analysis on the Donor State, Donor Is Teacher and Donor Zip variable of the complete observations reveals no further abnormalies.

### Donations

- Performed missing data pattern on the table and found no observations with missing values in any variables

- Gathered summary statistics Project ID, Donor ID, Donation Included Optional Donation, Donation Amount and Donation Received Date. Summary statistics showed that there are 2024554 unique donors contributing 4687844 donations to 901965 unique projects. The donation amount ranges from 0.01 dollars to 60000 dollars. The donation recieved date spans from 2012/10/08 to 2018/05/09.

- The extreme values of donation amount warrants further investigation. Using distribution analysis on the Donation Amount reveals that the 0.5% qunatile and 99.5% quantile of the Donation Amount are 1 and 750 respectively. In total there are 377031 observations that are within either quantile, with Donation Amount <=1 taking up the majority at 354405 observations.

- The 60000 Donation Amount value comes from a single Donation observation made in 2013/04/25. While this is not invalid data, it should be noted as a outlier as the next closest value comes in at 31856.6, which is slightly larger than half of the maximum value.

- A closer examination on donation amounts lesser than 1 dollar shows that there are 350 such observation. The distribution of these observations evens out across the dollar spectrum, suggesting that such behavior is not abnormal.

- With no abnormalies found in the data, all observations are included in the clean dataset.

### Projects.csv

- Excluded Project Title, Essay, Short Description and Need Statement. While they may be useful in sentimental analysis, the primary focus is to discover donor clusters and the type of projects they donate to using quantitative data. However, the data is not hidden as they are still useful in getting context.

- Performed missing data pattern analysis on the remaining variables, found 826739 observations will no missing values, 283227 observations with missing Project Fully Funded Date values, 14 missing Project Expiry Date and Project Fully Funded Date values, 7 missing Project Resource Category values, and 31 observations missing values in 3 or more variables. 

- Of the 283227 obervations with missing Project Fully Funded Date, 241367 have Project Current Status value of Expired while the rest have a value of Live. As the projects status justifies the reason for no values in Project Fully Funded Date, these observations are considered valid for analysis.

- 7 observations with missing Project Resource Category are marked as Fully Funded. Joining these observation with the Resource table shows that all 7 projects have valid Resource observations. These observations are assigned a new "Uncategorized" value to the Project Resource Category variable, deplicating them as valid Project observations but with no Project Resource Category values.

- The 14 observations with missing Project Expiry Date and Project Fully Funded Date values are marked as Expired in the Project Current Status. Of which, only 1 Project (f4433bd3e073c91c49184887374a1de9) has donations given to it. Considering that the analysis is concerned with donor segregation, the projects in this group without any donations are hidden and excluded form the table as they are not useful for the analysis. The sole project withh donation is kept.

- There are 29 observations missing Project Subject Category Tree, Project Subject Subcategory Tree and Project Resource Category values. Of which, 11 of those observations have a Current Project Status as expired and does not have a Project Fully Funded Date value. Joining these observations with the Donations table shows that 19 of the Project actually received donations, suggesting that these Project observations are valid data. To handle the missing values in the 3 variables, these observations are assigned a value of "Uncategorized" to those variables to indicate that they have missing data.

- There are 2 observations that are missing 9 values in 9 variables from Project Subject Category Tree onwards. A closer examination suggest that they belong to the same observation: The first observation contains an essay requesting for opportunites for students to do hands-on enginnering, while the second observation contain seemingly misplaced values such as "Math & Science", "Applied Sciences, Mathematics" etc. Likewise, the project resource required has "thames & kosmos robotics: smart machines science kit" recorded in the Resource Item Name variable. The fact that these 2 observation rows are next to each other in the table supports the hypothesis. Due to these reasons, the 2 observations are joined together to form 1 complete obersvation.

- To trim down the amount of irrelavent data pertaining to donor segmentation, all observations in the Projects table without donations are hidden and excluded

- Created new variable Project Posted Duration (Days) to record the number of days that the project has been posted. Checked that the duration is valid and store the result as a boolean flag in Valid Duration variable; both Project Posted Date and Project Expiration Dates are not missing and the date difference between the 2 must be postive. The duration check found and marked out 29 observations with negative Project Posted Duration (Days) value. Of these 29 projects, 10 of them received donations.

- Because the analysis is made with regards to donor segmentation, only projects that received any donations are of interest. As such, the Projects table is joined with a summarized Donations by Project ID table to form the Project with Donations table. The resulting table contains 873849 observations

- Changed Teacher Project Posted Sequence's data type to numeric and modeling type to continous.

- Performed distribution analysis on the Projects with Dontaions table and found no abnormalities except for 10 observations with negative Project Posted Duration (Days) value, which have already been marked as invalid by the Valid Duration flag.

- Notably, the distribution analysis did show some Teach Project Posted Sequence with extremely high values. However, cross checking with the Teachers table shows that these teachers had been posting projects on Donors Choose for a very long time, some of them with more than 10 years on the platform. As such, those values are considered valid for analysis.

### Teachers

- Joined the Teachers table with Projects with Donations table to remove Teacher observations of projects that did not receive any dontaions. The new table, named Teachers with Donated Projects, contains 338378 observations.

- Missing data pattern analysis reveals that there are 23 observations without Teacher Prefix values. These observations are assigned the value of "Unknown" as it will be inaccurate to assume the gender of the teacher when the project is proposed.

### Schools

- Joined the School table with Projects with Donations table to remove Schools observations of projects that did not receive any dontaions. The new table, named Schools with Donated Projects, contains 68923 observations.

- Missing data patterna analysis reveals 2 observations with missing values in School County, 151 observations missing values in School City variable, 948 observations missing School Percentage Free Lunch values and 67 observations missing School Percentage Free Lunch and School City values.

- Of the observations with missing variable, the ones of concern are observations with missing School Percentage Free Lunch values; this is because this variable is used to indicate if the most of school's students comes from lower income families, an fact that is shown to potential donors on the projects page accoding to the Donors Choose website. Given that these School observations has donated projects, they remain relevant to the analysis and hence are retained in the table. However, they are marked as false in a new formula boolean column Valid Free Lunch Percentage to indicate that they have missing data in the field.

- Likewise, School City, County and District infromation are excluded from the Schools with Donated Projects table as they are not going to be used in the donor's segmentation analysis.

- A distribution analysis is performed on the School Metro Type, School Percentage Free Lunch, School State and Number of Projects with Donations. No abnormalities were found in School Metro Type, School Percentage Free Lunch and School State. There are schools with large number of projects with donations, but that is not unexpected; the schools with 161 or more projects with donations (160 is th 99.75 percentile for overall Number of Projects with Donations values) have a mean School Percentage Free Lunch of 75%, implying that the schools with majority of students from low income households are indeed benefiting form the platfrom by having their needs projects funded.

### Resources

- The Resource table is not cleaned as the analysis does not require the data containd within at the moment.

## Data Exploration

### Donors

- Exploration of the Donors table showed that majority (89.99%) of the donors are not teachers. Califonia state has the largest number of Donors, followed by New York and Texas. The 3 states combine contains 25% of the total number of donors on the platform. On the other hand Vermont, North Dakota and Wyoming have the least number of DOnors, accounting for less than 0.5% of the total number of donors.

### Donations

- Of all the donations made to the projects, 85% of those included the optional 15% donation to Donor Choose.

- Based on exploration done on the Donations table during data cleaning, it is known that the distribtuion of amount donated per donation shows that the amount varies greatly, ranging from 0.01 to 60000. With the 10th percentile being 3 dollars and the 99.5th percentile being 750 dollars.

- Focusing on the upper limits of donation amount reveals that 90% of the donations made within this end of the spectrum amounts to less than 2400 dollars. 99.5% of the donations amounts to 10000 dollars or less. The single 60000 dollor donation, along with the next few largest donations, are considered more as an outlier rather than the norm. These observations will have to be excluded during clustering.


